ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'SPACE_RENTAL';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'SERVICE_INCOME';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'OTHER_INCOME';

CREATE TYPE "ExpenseEntryKind" AS ENUM ('EXPENSE', 'INCOME');

ALTER TABLE "RecurringExpenseRule"
ADD COLUMN "kind" "ExpenseEntryKind" NOT NULL DEFAULT 'EXPENSE';

ALTER TABLE "Expense"
ADD COLUMN "kind" "ExpenseEntryKind" NOT NULL DEFAULT 'EXPENSE';
